# Event name
name: on_push

# When the event should run
on:
  push:
    branches:
      - main

# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
# What steps within each job