# Event name
name: on_push

# When the event should run
on:
  push:
    branches:
      - main

# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
      - name: Run tests with Maven
        working-directory: webdriver_java
        run: mvn test